### ISSUE TITLE
Enhancement -- Allow option to choose direction of split opening

### ISSUE THREAD

**Issue by tallguyjenks** [lynchjames/obsidian-mind-map#1]
current the mind map split opens under the current document, this is probably for the best, and in default theme likely ideal, but for those of us with andy mode it kinda throws the pages out of wack formatting wise and at one point caused the mind map to be hidden entirely under the current notes i had open and was only shown after i closed the open note.

tl;dr : option to select opening mind map below or beside the current note :)

**Comment by lynchjames** [comment]
Yes, issues with this were also reported under #4. I will add a plugin setting for this.

**Comment by tallguyjenks** [comment]
ah, my bad, closing due to duplicate

**Comment by lynchjames** [comment]
No problem. You raised this issue first but I commented on #4 first!

Setting is now in place in [1.0.1](https://github.com/lynchjames/obsidian-mind-map/releases/tag/1.0.1).
