### ISSUE TITLE
Can't see text above the mindmap lines properly 

### ISSUE THREAD

**Issue by Grover3293** [lynchjames/obsidian-mind-map#13]
![image](https://user-images.githubusercontent.com/68772919/101993422-895f5800-3ce0-11eb-8657-19f1e8a5a972.png)

**Comment by lynchjames** [comment]
Thanks for raising this.

I will be adding settings for node height, vertical spacing and horizontal spacing in the next release. Hopefully that gives you the options you need for the text to be displayed correctly.

**Comment by Grover3293** [comment]
thank you very much 
and thanks for the awesome plugin 
i had to use miro embeds for mind maps

**Comment by lynchjames** [comment]
Plugin options now available in [1.1.0](https://github.com/lynchjames/obsidian-mind-map/releases/tag/1.1.0).

You should be able to have the text presented correctly by adjusting the Node Min Height and Line Height settings.
