### ISSUE TITLE
Bug -- YAML front matter is picked up by mind map

### ISSUE THREAD

**Issue by tallguyjenks** [lynchjames/obsidian-mind-map#2]
![image](https://user-images.githubusercontent.com/29872822/101306069-d9c64980-37f8-11eb-926d-c6f2a560c73f.png)

**Comment by lynchjames** [comment]
Thanks for raising this. I will exclude front matter from the markdown parsed for the mind map.

**Comment by lynchjames** [comment]
This should be fixed in [1.0.3](https://github.com/lynchjames/obsidian-mind-map/releases/tag/1.0.3).
