### ISSUE TITLE
Enhancement - Allow to Pin Mindmap

### ISSUE THREAD

**Issue by Quorafind** [lynchjames/obsidian-mind-map#3]
One use case: 

I usually used mermaid as a permant mindmap before, but it could not collapse those nodes. 

I don't know if it is possible to make a mindmap be fixed. But it will be useful when I want to pin it.

**Comment by lynchjames** [comment]
This is now available in [1.0.2](https://github.com/lynchjames/obsidian-mind-map/releases/tag/1.0.2) as an option in the [preview more options menu](https://github.com/lynchjames/obsidian-mind-map#preview-more-options-menu).
