### ISSUE TITLE
Not compatible with sliding pane template

### ISSUE THREAD

**Issue by psyguy** [lynchjames/obsidian-mind-map#4]
Hi James,
Thanks for making this plugin!

There is an issue with [Sliding Panes (Andy Matuschak Mode) Obsidian Plugin](https://github.com/deathau/sliding-panes-obsidian): Since sliding panes do not support (horizontal) splitting of notes, the mind map cannot be seen unless the main note is closed.

I don't know if there can be a fix for this (as it is an issue with the theme, and is still [under consideration](https://github.com/deathau/sliding-panes-obsidian/issues/14)), but I wanted to report it anyway :).

**Comment by macbikegeek** [comment]
Confirming this issue as well. Thanks.

**Comment by lynchjames** [comment]
I will add a setting to allow you to choose whether the new pane for the preview is a horizontal or vertical split. I've tested with a vertical split and this appears to work fine with the Sliding Panes plugin.

**Comment by lynchjames** [comment]
Setting is now in place in [1.0.1](https://github.com/lynchjames/obsidian-mind-map/releases/tag/1.0.1).
