### ISSUE TITLE
Bug : Faied to load plugin 

### ISSUE THREAD

**Issue by alwinlin23** [lynchjames/obsidian-mind-map#6]
![image](https://user-images.githubusercontent.com/2699243/101485078-96551200-3995-11eb-8ab1-7140c2c8ac8f.png)

**Comment by alwinlin23** [comment]
While trying to find logs under .obsidian/plugins/obsidian-mind-map, main.js is not found....
This might be some network problem with installation.

**Comment by lynchjames** [comment]
I've recently updated with another release (1.0.0). Can you try installing again to see if it is successful?

**Comment by alwinlin23** [comment]
> I've recently updated with another release (1.0.0). Can you try installing again to see if it is successful?

it works now 👍
