### ISSUE TITLE
Bug: Extra relation in Mind Map

### ISSUE THREAD

**Issue by phaalonso** [lynchjames/obsidian-mind-map#8]
Probaly this need to be treated in the parser
![image](https://user-images.githubusercontent.com/26033899/101563452-040a3980-39a8-11eb-9b96-264c3de6abdc.png)
![image](https://user-images.githubusercontent.com/26033899/101563711-8b57ad00-39a8-11eb-85fa-ef39bca9673f.png)
![image](https://user-images.githubusercontent.com/26033899/101563617-5b100e80-39a8-11eb-8c23-9fd34ca3bee1.png)

**Comment by lynchjames** [comment]
This appears to be caused by headings you have as a list item e.g. `- ### Equidade`. I think this is invalid markdown which may cause it to be rendering unexpectedly by Markmap.
